// Types
import type { Metadata } from "next"

// Assets
import { Manrope } from "next/font/google"

// Styles
import GlobalStyle from "@styles/global"

// Libraries
import StyledComponentsRegistry from "@lib/registry"

// Components
import PageWrapper from "@components/layout/PageWrapper/PageWrapper"

const manropeFont = Manrope({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={manropeFont.className}>
      <StyledComponentsRegistry>
        <GlobalStyle />

        <PageWrapper>{children}</PageWrapper>
      </StyledComponentsRegistry>
    </body>
  </html>
)

export default RootLayout
